// 节点类型枚举
export const NODE_TYPES = {
  BOM: 'BOM',
  COMPONENT: 'COMPONENT',
  PROJECT: 'PROJECT',
  TEMPLATE: 'TEMPLATE',
  PSYSTEM: 'PSYSTEM',
  SPECIFICATION: 'SPECIFICATION',
  PTYPE: 'PTYPE',
  CONFIGURATION: 'CONFIGURATION'
} as const; 